- name: Install FireFox
  hosts: group_clients_windows
  tasks:
    - name: Check if C:\Temp exists
      ansible.windows.win_stat:
        path: C:\Temp
      register: temp_folder

    - name: Create C:\Temp if it does not exist
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      when: not temp_folder.stat.exists

    - name: Download Firefox installer
      ansible.windows.win_get_url:
        url: https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=de
        dest: C:\Temp\firefox_installer.msi

    - name: Install Firefox
      ansible.windows.win_package:
        path: C:\Temp\firefox_installer.msi
        arguments: /quiet
        state: present
    
    # Notepad++
    - name: Download Notepad++ installer
      ansible.windows.win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.8.1/npp.8.8.1.Installer.x64.exe
        dest: C:\Temp\npp_installer.exe

    - name: Install Notepad++
      ansible.windows.win_package:
        path: C:\Temp\npp_installer.exe
        arguments: /S
        state: present
  
    - name: Download Greenshot installer
      ansible.windows.win_get_url:
        url: https://github.com/greenshot/greenshot/releases/download/Greenshot-RELEASE-1.2.10.6/Greenshot-INSTALLER-1.2.10.6-RELEASE.exe
        dest: C:\Temp\greenshot_installer.exe

    - name: Install Greenshot silently
      ansible.windows.win_shell: |
        Start-Process -FilePath "C:\Temp\greenshot_installer.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES" -Wait
    
    - name: Download PuTTY installer
      ansible.windows.win_get_url:
        url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.83-installer.msi
        dest: C:\Temp\putty_installer.msi

    - name: Install PuTTY
      ansible.windows.win_package:
        path: C:\Temp\putty_installer.msi
        state: present

    - name: Download VLC installer
      ansible.windows.win_get_url:
        url: https://ftp.fau.de/videolan/vlc/3.0.21/win64/vlc-3.0.21-win64.exe
        dest: C:\Temp\vlc_installer.exe

    - name: Install VLC
      ansible.windows.win_package:
        path: C:\Temp\vlc_installer.exe
        arguments: /S
        state: present
	
    - name: Download PDF XChange
      ansible.windows.win_get_url:
        url: https://www.pdf-xchange.de/DL/tracker10/editor-msi64-tracker.php
        dest: C:\Temp\pdf_xchange.msi
        
    - name: Install PDF XChange via MSI
      ansible.windows.win_shell: |
        msiexec.exe /i "C:\Temp\pdf_xchange.msi" /quiet /NORESTART
      args:
        executable: cmd
