- name: Install FireFox
  hosts: group_clients_windows
  tasks:
    - name: Check if C:\Temp exists
      ansible.windows.win_stat:
        path: C:\Temp
      register: temp_folder

    - name: Create C:\Temp if it does not exist
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      when: not temp_folder.stat.exists
  
    - name: Download Firefox installer
      ansible.windows.win_get_url:
        url: https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=de
        dest: C:\Temp\firefox_installer.msi

    - name: Install Firefox
      ansible.windows.win_package:
        path: C:\Temp\firefox_installer.msi
        arguments: /quiet
        state: present
    
    # Notepad++
    - name: Download Notepad++ installer
      ansible.windows.win_get_url:
        url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.8.1/npp.8.8.1.Installer.x64.exe
        dest: C:\Temp\npp_installer.exe

    - name: Install Notepad++
      ansible.windows.win_package:
        path: C:\Temp\npp_installer.exe
        arguments: /S
        state: present

    # Greenshot via winget
    - name: Install Greenshot via winget
        ansible.windows.win_powershell: |
        winget install -e --id Greenshot.Greenshot --silent --accept-package-agreements --accept-source-agreements
      register: greenshot_result
      changed_when: "'already installed' not in greenshot_result.stdout"

    # PuTTY
    - name: Download PuTTY installer
      ansible.windows.win_get_url:
        url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.83-installer.msi
        dest: C:\Temp\putty_installer.msi

    - name: Install PuTTY
      ansible.windows.win_package:
        path: C:\Temp\putty_installer.msi
        state: present

    # VLC Media Player
    - name: Download VLC installer
      ansible.windows.win_get_url:
        url: https://ftp.fau.de/videolan/vlc/3.0.21/win64/vlc-3.0.21-win64.exe
        dest: C:\Temp\vlc_installer.exe

    - name: Install VLC
      ansible.windows.win_package:
        path: C:\Temp\vlc_installer.exe
        arguments: /S
        state: present

    # Adobe Acrobat Reader
    - name: Download Acrobat Reader installer
      ansible.windows.win_get_url:
        url: blob:https://get.adobe.com/fcbabff6-84c3-43a4-8244-8eb8e7689c7a
        dest: C:\Temp\acrobat_installer.exe

    - name: Install Adobe Acrobat Reader
      ansible.windows.win_package:
        path: C:\Temp\acrobat_installer.exe
        arguments: -sfx_nu /sALL /msi EULA_ACCEPT=YES
        state: present
