- name: Install FireFox
  hosts: group_clients_windows
  tasks:
    - name: Check if C:\Temp exists
      ansible.windows.win_stat:
        path: C:\Temp
      register: temp_folder

    - name: Create C:\Temp if it does not exist
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      when: not temp_folder.stat.exists
  
    - name: Download Greenshot installer
      ansible.windows.win_get_url:
        url: https://github.com/greenshot/greenshot/releases/download/Greenshot-RELEASE-1.2.10.6/Greenshot-INSTALLER-1.2.10.6-RELEASE.exe
        dest: C:\Temp\greenshot_installer.exe
  
    - name: Kill Greenshot if already running
      ansible.windows.win_shell: |
        Get-Process Greenshot -ErrorAction SilentlyContinue | Stop-Process -Force
      ignore_errors: true
    
    - name: Install Greenshot silently
      ansible.windows.win_shell: |
        Start-Process -FilePath "C:\Temp\greenshot_installer.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /LOG=C:\Windows\Logs\Software\GreenShot-Install.log" -Wait
    
    - name: Wait for installer to finish
      ansible.windows.win_shell: |
        while (Get-Process | Where-Object { $_.ProcessName -like "greenshot*" }) {
          Start-Sleep -Seconds 3
        }
    
    - name: Confirm installation
      ansible.windows.win_stat:
        path: "C:\\Program Files\\Greenshot\\Greenshot.exe"
      register: greenshot_installed
    
    - name: Report result
      debug:
        msg: "Greenshot wurde installiert!"
      when: greenshot_installed.stat.exists
    
    # PuTTY
    - name: Download PuTTY installer
      ansible.windows.win_get_url:
        url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.83-installer.msi
        dest: C:\Temp\putty_installer.msi

    - name: Install PuTTY
      ansible.windows.win_package:
        path: C:\Temp\putty_installer.msi
        state: present

    # VLC Media Player
    - name: Download VLC installer
      ansible.windows.win_get_url:
        url: https://ftp.fau.de/videolan/vlc/3.0.21/win64/vlc-3.0.21-win64.exe
        dest: C:\Temp\vlc_installer.exe

    - name: Install VLC
      ansible.windows.win_package:
        path: C:\Temp\vlc_installer.exe
        arguments: /S
        state: present

    # Adobe Acrobat Reader
    - name: Download Acrobat Reader installer
      ansible.windows.win_get_url:
        url: blob:https://get.adobe.com/fcbabff6-84c3-43a4-8244-8eb8e7689c7a
        dest: C:\Temp\acrobat_installer.exe

    - name: Install Adobe Acrobat Reader
      ansible.windows.win_package:
        path: C:\Temp\acrobat_installer.exe
        arguments: -sfx_nu /sALL /msi EULA_ACCEPT=YES
        state: present
