- name: Install FireFox
  hosts: group_clients_windows
  tasks:
    - name: Check if C:\Temp exists
      ansible.windows.win_stat:
        path: C:\Temp
      register: temp_folder

    - name: Create C:\Temp if it does not exist
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      when: not temp_folder.stat.exists

    # Adobe Acrobat Reader
    - name: Download Acrobat Reader installer
      ansible.windows.win_get_url:
        url: https://get.adobe.com/uk/reader/download?os=Windows+10&name=Reader+2025.001.20467+English+UK+Windows%2864Bit%29&lang=uk&nativeOs=Windows+10&accepted=cr&declined=mss&preInstalled=&site=landing
        dest: C:\Temp\acrobat_installer.exe

    - name: Install Adobe Acrobat Reader
      ansible.windows.win_package:
        path: C:\Temp\acrobat_installer.exe
        arguments: -sfx_nu /sALL /msi EULA_ACCEPT=YES
        state: present
