- name: Install FireFox
  hosts: group_clients_windows
  tasks:
    - name: Check if C:\Temp exists
      ansible.windows.win_stat:
        path: C:\Temp
      register: temp_folder

    - name: Create C:\Temp if it does not exist
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      when: not temp_folder.stat.exists

    # Adobe Acrobat Reader
    - name: Download PDF XChange
      ansible.windows.win_get_url:
        url: https://www.pdf-xchange.de/DL/tracker10/editor-msi64-tracker.php
        dest: C:\Temp\pdf_xchange.msi

    - name: Install Adobe Reader via MSI
      ansible.windows.win_shell: |
        msiexec.exe /i "C:\Temp\pdf_xchange.msi" /VERYSILENT /NORESTART
      args:
        executable: cmd
