- name: Install FireFox
  hosts: group_clients_windows
  tasks:
    # Adobe Acrobat Reader
    - name: Install Adobe Reader via MSI
      ansible.windows.win_shell: |
        msiexec.exe /i "C:\Temp\pdf_xchange.msi" /quiet /NORESTART
      args:
        executable: cmd
