- name: Install software using winget on Windows
  hosts: windows  # Deine Windows-Gruppe oder spezifische Hosts
  tasks:
    - name: Install Firefox
      win_command: winget install -e --id Mozilla.Firefox
