---
- name: Windows in AD-Domäne aufnehmen
  hosts: client2
  tasks:

    - name: Domäne joinen
      win_domain_membership:
        dns_domain_name: "test.ansible"
        domain_admin_user: "ansible"
        domain_admin_password: "insecure"
        hostname: "DC"
        state: domain
      register: domain_state

    - name: Neustart nach Domain-Join (wenn nötig)
      win_reboot:
        msg: "System wird neu gestartet, um der Domäne beizutreten."
        pre_reboot_delay: 5
      when: domain_state.reboot_required
