- name: Install FireFox
  hosts: windows_clients
  tasks:
    - name: Download Firefox installer
      ansible.windows.win_get_url:
        url: https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64&lang=de
        dest: C:\Temp\firefox_installer.msi

    - name: Install Firefox
      ansible.windows.win_package:
        path: C:\Temp\firefox_installer.msi
        arguments: /quiet
        state: present
